name: Build and Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Update Version in Application
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}          
          MAINTAINER_EMAIL="${{ github.actor }}@users.noreply.github.com"
          BUILD_DATE=$(date -u +'%Y-%m-%d')
          COMMIT_HASH=${{ github.sha }}

          echo "New Tag: $TAG_NAME"
          echo "Maintainer: $MAINTAINER_EMAIL"
          echo "Build Date: $BUILD_DATE"
          echo "Commit Hash: $COMMIT_HASH"
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Build package
        run: |
          set -e
          echo "Python version:"
          python --version
          echo "Pip version:"
          pip --version
          echo "Building the package..."
          python setup.py sdist bdist_wheel
          echo "Current dir content:"
          ls -l dist

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: /dist/project_cli-0.0.2.tar.gz, /dist/project_cli-0.0.2-py3-none-any.whl
